// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA31_smApKt5pGz8cVk7NGTZEQmm-EH67k',
    appId: '1:757015184519:web:4c87a25b9391166a60e422',
    messagingSenderId: '757015184519',
    projectId: 'text-to-speech-app-7c322',
    authDomain: 'text-to-speech-app-7c322.firebaseapp.com',
    storageBucket: 'text-to-speech-app-7c322.appspot.com',
    measurementId: 'G-757TB5G3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtr_bw0WB0rFg5HrwYKDg03NJOpfT2bM',
    appId: '1:757015184519:android:4d599075a495b64560e422',
    messagingSenderId: '757015184519',
    projectId: 'text-to-speech-app-7c322',
    storageBucket: 'text-to-speech-app-7c322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJuPhwpZqBthJtFtzx2AVyzx2DfKVQwVk',
    appId: '1:757015184519:ios:5f4f7e2a82e1983d60e422',
    messagingSenderId: '757015184519',
    projectId: 'text-to-speech-app-7c322',
    storageBucket: 'text-to-speech-app-7c322.appspot.com',
    iosBundleId: 'com.example.textToSpeech',
  );
}
